version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - shared_proxy_net

  api:
    build: .
    container_name: python-api
    command: gunicorn --bind 0.0.0.0:5000 -k eventlet --workers 1 api_server:app
    restart: always
    depends_on:
      - redis
    networks:
      - shared_proxy_net

  worker:
    build: .
    container_name: api-worker
    command: celery -A celery_task.celery worker --loglevel=info --pool=eventlet
    restart: always
    depends_on:
      - redis
    networks:
      - shared_proxy_net

networks:
  shared_proxy_net:
    external: true
